// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phwjuvecnfvyeumpbqbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBod2p1dmVjbmZ2eWV1bXBicWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTAwMTcsImV4cCI6MjA1OTk2NjAxN30.YBxfOGjxIffhrf4bBEYyg4679CTKo74NpwEUY07JyHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);